apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: manyfacedgod/kub-demo-tasks:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: AUTH_ADDRESS
              # value: "10.105.129.220"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks
